resources:
  - name: lattice
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/lattice.git
      branch: concourse
  - name: diego-release
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/diego-release.git
      branch: master
  - name: cf-release
    type: git
    source:
      uri: https://github.com/cloudfoundry/cf-release.git
      branch: runtime-passed
  - name: lattice-tar
    type: s3
    source:
      bucket: lattice-concourse
      private: true
      regexp: lattice-v(.*).tgz
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}
  - name: ltc-tar
    type: s3
    source:
      bucket: lattice-concourse
      regexp: ltc-v(.*).tgz
      private: true
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}

jobs:
  - name: unit-test-ltc
    plan:
      - get: lattice
        trigger: true
      - task: unit-test-ltc
        file: lattice/concourse/tasks/unit-test-ltc/task.yml
  - name: unit-test-s3tool
    plan:
      - get: lattice
        trigger: true
      - task: unit-test-s3tool
        file: lattice/concourse/tasks/unit-test-s3tool/task.yml
  - name: unit-test-tee2metron
    plan:
      - get: lattice
        trigger: true
      - task: unit-test-tee2metron
        file: lattice/concourse/tasks/unit-test-tee2metron/task.yml
  - name: compile-lattice-tar
    plan:
      - aggregate:
        - get: lattice
          passed:
            - unit-test-s3tool
            - unit-test-tee2metron
          trigger: true
        - get: diego-release
        - get: cf-release
      - task: compile-lattice-tar
        file: lattice/concourse/tasks/compile-lattice-tar/task.yml
      - put: lattice-tar
        params:
          from: lattice/build/lattice-v(.*).tgz
          to: /experimental/lattice/

  - name: compile-ltc
    plan:
      - get: lattice
        passed:
          - unit-test-ltc
        trigger: true
      - task: compile-ltc
        file: lattice/concourse/tasks/compile-ltc/task.yml
      - put: ltc-tar
        params:
          from: lattice/build/ltc-v(.*).tgz
          to: /experimental/ltc/
