resources:
  - name: lattice
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/lattice.git
      branch: concourse
  - name: diego-release
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/diego-release.git
      branch: master
  - name: cf-release
    type: git
    source:
      uri: https://github.com/cloudfoundry/cf-release.git
      branch: runtime-passed
  - name: lattice-tar
    type: s3
    source:
      bucket: lattice-concourse
      private: true
      regexp: lattice-v(.*).tgz
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}
  - name: ltc-tar
    type: s3
    source:
      bucket: lattice-concourse
      regexp: ltc-v(.*).tgz
      private: true
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}

jobs:
  - name: ltc-unit-test
    plan:
      - aggregate:
        - get: lattice
          trigger: true
        - get: diego-release
      - task: ltc-unit-test
        file: lattice/concourse/tasks/ltc-unit-test/task.yml
  - name: s3tool-unit-test
    plan:
      - get: lattice
        trigger: true
      - task: s3tool-unit-test
        file: lattice/concourse/tasks/s3tool-unit-test/task.yml
  - name: tee2metron-unit-test
    plan:
      - get: lattice
        trigger: true
      - task: tee2metron-unit-test
        file: lattice/concourse/tasks/tee2metron-unit-test/task.yml
  - name: compile-lattice-tar
    plan:
      - aggregate:
        - get: lattice
          passed:
            - s3tool-unit-test
            - tee2metron-unit-test
          trigger: true
        - get: diego-release
        - get: cf-release
      - task: compile-lattice-tar
        file: lattice/concourse/tasks/compile-lattice-tar/task.yml
      - put: lattice-tar
        params:
          from: lattice/build/lattice-v(.*).tgz
          to: /experimental/lattice/
  - name: compile-ltc
    plan:
      - aggregate:
        - get: lattice
          passed:
            - ltc-unit-test
          trigger: true
        - get: diego-release
      - task: compile-ltc
        file: lattice/concourse/tasks/compile-ltc/task.yml
      - put: ltc-tar
        params:
          from: lattice/build/ltc-v(.*).tgz
          to: /experimental/ltc/
